name: Deploy BE To AWS

on:
  push:
    branches: [ BE_Deploy ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd ${{ github.workspace }}/API && dotnet restore
    - name: Build
      run: cd ${{ github.workspace }}/API && dotnet build --no-restore
    - name: Publish
      run: cd ${{ github.workspace }}/API && dotnet publish -c Release -o '${{ github.workspace }}/out'
    - name: Zip Package
      run:
        cd ${{ github.workspace }}/out && powershell Compress-Archive -DestinationPath ${{ github.workspace }}/out.zip -path *
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Test Window Env
        environment_name: Testwindowenv-env
#         version_label: ${{ github.run_id }}
        version_label: 1.0.0
        region: ap-southeast-1
        deployment_package: ${{ github.workspace }}/out.zip
#         use_existing_version_if_available: false      
